---
name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:
jobs:
  test_latest:
    name: Test with latest consul
    runs-on: ubuntu-latest
    # Whenever the Go version is updated here, .promu.yml
    # should also be updated.
    container:
      image: quay.io/prometheus/golang-builder:1.19-base
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          consul_version: 1.14.3
  test_older:
    name: Test with older consul
    runs-on: ubuntu-latest
    # Whenever the Go version is updated here, .promu.yml
    # should also be updated.
    container:
      image: quay.io/prometheus/golang-builder:1.19-base
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          consul_version: 1.12.8

  build:
    name: Build Consul Exporter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [ 0, 1, 2, 3, 4, 5 ]
    steps:
      - uses: actions/checkout@v3
      - uses: prometheus/promci@v0.0.2
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 6
          thread: ${{ matrix.thread }}

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '<1.19'
      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.49.0
