---
name: Publish
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
jobs:
  ci:
    name: Run ci
    uses: ./.github/workflows/ci.yml

  publish_main:
    name: Publish main branch artefacts
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - uses: prometheus/promci@v0.0.2
      - uses: ./.github/promci/actions/publish_main
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
